name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "READMDE.md"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "READMDE.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: seelerei0130/rasamukun

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Pull Builded Image
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.ACTION_SSH_HOST }}
          username: ${{ secrets.ACTION_SSH_USER }}
          key: ${{ secrets.ACTION_SSH_KEY }}
          passphrase: ${{ secrets.ACTION_SSH_PASSPHRASE }}
          script: |
            docker pull seelerei0130/rasamukun
            cd app/rasamukun
            docker-compose up -d
